behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024          
      buffer_size: 20480        
      learning_rate: 2.5e-4     
      beta: 1.0e-4             
      epsilon: 0.15            
      lambd: 0.95              
      num_epoch: 5             
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true          
      hidden_units: 256        
      num_layers: 3             
    reward_signals:
      gail:
        strength: 0.9
        demo_path: Demos/record-New_0.demo
    max_steps: 1000000         
    time_horizon: 512         
    summary_freq: 5000          
